# Generated by Django 6.1.1 on 2026-10-03 17:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articulos',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
    ]
