# Generated by Django 6.1.1 on 2026-10-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articulos_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='crated_ad',
            new_name='crated_at',
        ),
    ]
